spring.application.name=test1
spring.datasource.url=jdbc:postgresql://localhost:5432/lead_db
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=2CaXAPLsH0qeLQwSzHGb1KPalnwS2ReXn5N73xu6WeADIqIh
jwt.expiration=86400000